cs481-ekh/f22-kneed-for-speed

.github/workflows/github-actions.yml, README.md, build.sh, test.sh
Once branch 71 and this branch are successfully merged, we should be able to accurately see the results of our Workflow in the README.
=> Add status badges to readme

.github/workflows/github-actions.yml, build.sh, test.sh
I'm not sure how familiar the rest of you are with yaml but it relies on indentation to run properly. If you can but the .yml file in a validator and take a look at what the build.sh and test.sh files are doing, I'd appreciate those checks before we merge this.
The good news is it looks like from the latest commit I made, Actions no longer runs every time a commit is made.
=> 71 add workflow to GitHub actions

src/index.html, src/js/upload.js
=> 28 upload a file to the main page

src/js/canvas.js
Removed drawCircle() and drawTriangle() as well.
=> Moved 0, 0 location in drawSquare()

src/index.html, src/stylesheets/style.css
All images now respond properly to window size.
=> 88 use css andor javascript to make images change with window size

src/index.html, src/js/canvas.js, src/stylesheets/style.css
made minor changes to layout so it is more responsive, but the main issue was images.
=> 89 use css andor javascript to make sure the layout grid changes with window size

src/index.html, src/js/numeric-inputs.js, src/stylesheets/style.css
Completed 3 tasks for this story in one on accident. Plus and minus buttons now work. The number is now displayed to the user. A minimum and maximum number are in place, but these can be updated in the future based on the parameter they represent.
=> 103 add functionality to plus and minus buttons to increase and decrease numeric inputs

.github/workflows/github-actions.yml, build.sh, test.sh
At this point the hope is that the linter will lint any code anytime it is submitted to or pull requested to the main branch of our repo. In addition to JavaScript and HTML, it should lint all other languages unless we specify other wise and it should provide a detailed report in the actions tab of the repo. We can further modify the way it currently is to add a report to a folder if we choose to later.
=> 91 ensure current ci is doing what's expected

src/index.html, src/js/numeric-inputs.js
Can now use single clicks to add or subtract or continuously add or subtract while buttons are held down.
=> 104 enable buttons to continuously increase or decrease when held down

dockerfile
There are definitely some tools and unfamiliar commands needed to check the dockerfile's functionality. This is something I'm willing to help you all with if you'd like but it may take us awhile since most of you are using macOS while I used windows (I believe macOS makes using these tools easier). It may even be worth writing documentation to help others building off the dockerfile but because it's all on the internet anyways, maybe not.
=> 116 build docker image

src/index.html, src/stylesheets/style.css
I spent almost 3 hours working on creating responsive dials using CSS, but only committed to the branch once after I felt they were complete. They took a lot of fiddling.
Please let me know if they don't work well on different screen sizes!
=> dial elements created

src/index.html, src/js/parse-geometry.js
When a user uploads a file it is read as a text file and stored line by line as session data. 
The code then searches through the session data, find the start of the NODE section, and parses the node data into a 2D array of nodes, stopping at the start of the ELEMENTS section.
=> 131 parse node data from inp file

src/js/parse-geometry.js
Works well but is running slower. We may want to look into optimizing the code better or try to create a faster method next sprint. Up to the group.
=> used same method to parse elements as nodes

src/js/parse-geometry.js
All node and element data is stored in unique sessionStorage items.
naming conventions are:
'node node# x'
'node node# y'
'node node# z'
'element element# node 1'
'element element# node 2'
'element element# node 3'
'element element# node 4'
Node# and element# will change based on which node or element you want to access. May need to revisit element# naming next sprint. They didn't have their own numbers or names in the file, so they got numbered by their index in the array for now.
=> 133 store parsed data as session data

.github/workflows/node.js.yml, src/index.html, src/stylesheets/style.css
Just added a save button to the Webpage, It doesn't have any functionality yet.
=> Added Save Button to Webpage

src/js/parse-geometry.js
Discovered the .trim() method to remove extra spaces. Works really well. Easy fix.
=> used .trim() method to remove white space in .inp parser

src/js/parse-geometry.js
I decided to delete the extra arrays after they are created rather than finding a way to not create them.
=> used .splice() method to remove extra arrays

src/js/parse-geometry.js
Naming conventions for session storage items are:
'total nodes'
'initial node number'
=> 178 store starting node number and total number of nodes in session data

src/index.html, src/js/body-weight-dial.js, src/js/limb-alignment-dial.js
Added stepUp() and stepDown() calls to both dial JS files for their respective numeric value displays and updated the min and max of each value to those suggested by our sponsor.
=> 130 connect dial interaction to numeric display

src/js/parse-geometry.js
This PR will make it so the parser only fully works for bone .inp files temporarily, but I have code ready to go to add proper functionality for cartilage files for issues #236 and #249.
This code checks the tissue type of the .inp file when creating the initial element array and when putting the elements from that array into session storage. Because the original code only worked properly for bone files, it will still run correctly and the same as before if it detects a bone file. If it detects a cartilage file, for the moment, it will still create a node array, but will simply print out a console statement saying it has detected a cartilage file instead of creating the element array.
=> 235 parser creates 3 node element array for bone files

src/js/body-weight-dial.js, src/js/limb-alignment-dial.js
I found a simple solution for this that works but does not feel very fine-tuned. If time allows during this sprint, I might add another task for myself to see if this can be made a bit smoother.
Will this solution work for now? I also have a task to hopefully make the dial values increment based on their max value and 360 degrees, so turning them should only hit their max value after 1 full rotation. That task may help, too.
=> 239 disable dial turning clockwise if at max value

src/index.html, src/stylesheets/style.css
SDP Sticker is now a pop-up hover effect instead of using a scroll bar.
=> 238 fix sdp sticker

src/index.html, src/stylesheets/style.css
Text is now styled for the entire page and within every button. I also removed the extra space between the title and subtitle of the page and organized and labeled some of the additions to the stylesheet that have happened over the last few weeks.
=> 243 style remaining text

src/js/numeric-inputs.js
Buttons now increase/decrease numeric values much faster for a better user experience.
=> 244 increase rate of plus and minus buttons when held down

src/index.html, src/stylesheets/style.css
The canvas, the box around the file upload area, the main title text, and the parameter dials all have subtle shadows now. The old border around the dials is gone as well because the shadow replaced it/made it unnecessary.
=> 246 add shadow boxes to major UI elements

src/index.html, src/stylesheets/style.css
Buttons use custom fonts, turn blue & white when hovered over, turn orange & white when clicked, and are otherwise styled to match the standard default button.
=> 242 style buttons
